version: "3.8"

services:

  fake_power_elec:
    build:
      context: .
      dockerfile: docker/Dockerfile.power_elec_fake
    networks:
      custom_network:
        ipv4_address: 172.18.0.2
    command: ["--addr", "172.18.0.2", "--rotate-time", "50"]

  cloud_server:
    build:
      context: .
      dockerfile: docker/Dockerfile.cloud_server
    networks:
      custom_network:
        ipv4_address: 172.18.0.4
    command: ["--addr", "172.18.0.4", "--port", "9000"]

  exporter_ecoadapt:
    build:
      context: .
      dockerfile: docker/Dockerfile.exporter_ecoadapt
    networks:
      custom_network:
        ipv4_address: 172.18.0.3
    command: ["--cloud-addr", "ws://172.18.0.4", "--cloud-port", "9000", "--modbus-addr", "172.18.0.2", "--modbus-port", "502", "--log-level", "${LOG_LEVEL:-INFO}", "--time-interval", "60"]

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
